(function(){
    angular.module("TestStudio",[
        "ui.router",
        "root",
        "frontPage",
        "contactPage",
        "navbar",
        "typeTable",
        "pokeSearch"
    ]).run([function(){
    }]);
})();